### ISSUE TITLE
Enable cleanup of "leaked" pending authorizations

### ISSUE THREAD

**Issue by bifurcation** [ietf-wg-acme/acme#242]
Let's Encrypt tell me that they have had a few reports of buggy clients creating enough pending authorizations to saturate their rate limits, so they need a way for clients to clear these out.  These clients are also not keeping around authorization URLs, so they can't just go [deactivate](https://ietf-wg-acme.github.io/acme/#rfc.section.6.5.2) them.

My proposed solution would be to re-add the "authorizations" field to the account object, which got lost in the refactor in #208 or so.  Together with deactivation, enabling clients to enumerate authorization URLs would solve this problem.

You could also envision a more direct solution, offering an endpoint that just deletes all pending authorizations for a client or client+identifier.

**Comment by jsha** [comment]
> You could also envision a more direct solution, offering an endpoint that just deletes all pending authorizations for a client or client+identifier.

This is definitely too specific to these buggy clients.

For the `new-order` flow, the list of orders is sufficient. It's true that technically you can create authorizations through a separate, optional, `new-authz` flow. But Let's Encrypt has no plans to implement that flow, because other CAs have said they cannot / would not implement it, so Let's Encrypt implementing it would split the market. I'm inclined to say let's not complicate the protocol, and hypothetical clients that want to do the `new-authz` flow with some hypothetical server need to keep proper track of their authzs.

Also, I think the particular issue with hitting limits for pending authzs can be solved in several ways without modifying the protocol.

**Comment by sophie-h** [comment]
If #275 is merged, I would expect that a reasonable ACME server supporting new-authz would return an exiting authz, instead of giving a rate limit error. Or return existing authz from the beginning.

**Comment by daothithuy** [comment]
I'm digging I see now I do not want to because of the money that my site like I used to say I use this site to help my life and the existence and the good I can not be right to anybody And I Do not sell and do not give in. I can open my second leg for you to hear are the same

**Comment by bifurcation** [comment]
Closing as a result of WG decision at IETF 98
