### ISSUE TITLE
Require only one identifier for revocation

### ISSUE THREAD

**Issue by taowa** [ietf-wg-acme/acme#337]
Certificate Management - Certificate Revocation requires: `an account that holds authorizations for all of the identifiers in the certificate`.

This could allow an attacker who gains the ability to issue a certificate to prevent revocation by issuing a certificate for both the attacked domain, and a domain under their control.

# Example
Mallory gains temporary access to Bob's server. She has a certificate issued for bob.example and mallory.example. When Bob regains access to bob.example, he cannot revoke Mallory's certificate, as Mallory has erased the copy of the account and certificate keys on Bob's server (or she generated them on her own server). Seeing as Bob also doesn't have access to mallory.example, he cannot revoke the certificate.

# Proposed Changes
I propose that

```
The server MUST consider
at least the following accounts authorized for a given certificate:

[...]

* an account that holds authorizations for all of the identifiers in the
  certificate.
```

be changed to:

```
The server MUST consider
at least the following accounts authorized for a given certificate:

[...]

* an account that holds authorizations for **at least one** identifier in the
  certificate.
```

**Comment by jsha** [comment]
Thanks for proposing! We've discussed this change a bit, but unfortunately it's a non-starter because it puts multi-tenant certificates at extreme risk. Consider a hosting provider that consolidates multiple customers' hostnames onto a single certificate. If even a single customer moves their domain away, they could choose to revoke the whole certificate, disabling service for other, unrelated customers. And multi-tenant certificates are quite common. I think, unfortunately, this is an area that cannot be fully automated, and needs to lean on a CA's security incident reporting system and human discretion.
