### ISSUE TITLE
the DNS challenge should ONT only use any hostname start with underscore

### ISSUE THREAD

**Issue by cnzhangquan** [ietf-wg-acme/acme#437]
some of dns hosting provider's API does not allow hostname start with underscore
so, there should be a way to challenge with hostname which NOT start with underscore

**Comment by cpu** [comment]
Hi @cnzhangquan,

That's a problem that should be fixed by the hosting provider's API. The underscore character is valid in a non-hostname DNS selector as ACME uses it. [RFC 2181 Section 11](https://tools.ietf.org/html/rfc2181#section-11) describes this (though others might know of a better RFC to cite for this).
