### ISSUE TITLE
Use an extension for SimpleHTTP paths

### ISSUE THREAD

**Issue by jsha** [ietf-wg-acme/acme#9]
SimpleHTTP is currently defined to use a path that ends in the token value from the challenge, e.g. `.well-known/acme-challenge/evaGxfADs6pSRb2LAv9IZf17Dt3juxGJ-PCt92wr-oA`. Challenge responses are also required to have an empty Content-Type or 'application/jose+json`.

Since web servers commonly select a Content-Type based on file extension, and may set a default Content-Type for files with no extension, if would be useful to define an extension for the purpose. For instance, we could define the path to end in `.jose`.

**Comment by chriscroome** [comment]
You can use something like this for Apache:
```apache
<IfModule mod_headers.c>
  <LocationMatch "/.well-known/acme-challenge/*">
    Header set Content-Type "application/jose+json"
  </LocationMatch>
</IfModule>
```

But the spec now says:

> 4. Verify that the Content-Type header of the response is either absent, or has the value "text/plain".
> 
> https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#http

Which is the default for Apache.

**Comment by kelunik** [comment]
@chriscroome Adding a `<LocationMatch>` adds a overhead to every request just for validation. I think the updated spec with `text/plain` or no header is fine, extension would be fine as well.

**Comment by chriscroome** [comment]
@kelunik right, when the Let's Encrypt servers are updated to expect `text/plain` then there won't be a need to change the default Apache config, but at the moment the staging server does need `Content-Type "application/jose+json"` AFAIK.

**Comment by jsha** [comment]
Also FWIW Nginx will treat unknown extensions as `application/octet-stream` by default rather than `text/plain`

**Comment by kuba** [comment]
To be really precise, staging will never use `text/plain` for `simpleHTTP`. There is a new type of a challenge - `http-01`, which staging server already sends to clients - this one works with `text/plain`. Client has not yet been updated, https://github.com/letsencrypt/letsencrypt/issues/914.

**Comment by hlandau** [comment]
The specification currently requires that Content-Type be absent or be of `text/plain`, which seems very odd. It should at least be extended to also allow `application/octet-stream`. But I see no reason not to allow `application/jose+json` and indeed `application/json`. Bear in mind that IIRC some webservers may do MIME magic checking on the file contents in order to determine the content type, so even an extensionless file could end up with a Content-Type of e.g. `application/json`. An extension would also certainly help.

**Comment by hlandau** [comment]
I should also note that a Content-Type can be something like `text/plain; charset=utf-8`. The specification should probably clarify that when it says a Content-Type must be a given MIME type, arbitrary parameters must be accepted.

**Comment by bmw** [comment]
I just wanted to add that it looks like you cannot specify the `Content-Type` of a file without an extension in CPanel which will be a problem for some of our users who are using shared hosting.

**Comment by kelunik** [comment]
What's the way forward? Drop `content-type` requirement or just add an extension? I think it's something which should be changed before GA.

**Comment by My1** [comment]
stupid question why care about the mime-type at all the only things checked need to be the size (if the file is too big dont even download it) and the content, at least that's what I think.

any way makign stuff easier drop this in a .htaccess file in the acme-challenge dir:
<Files *>
ForceType text/plain
</Files>
that's what I have for now...

**Comment by kelunik** [comment]
@My1 Try using code fences:
```md
.```
code
.```
```

(without the `.`)

---

That solves it for Apache, but we're looking for a general solution here.

**Comment by hlandau** [comment]
I think an extension should be added and a small list of content types should be allowed, including (absent), text/plain, application/octet-stream, application/json and application/jose+json, i.e. the MIME types which are reasonable given the file content.

**Comment by webprofusion-chrisc** [comment]
Because this is being developed in a Windows free way I don't think you guys are hitting the same pain points as the (millions of) people who are using Windows/IIS, namely:

Please just allow the file to have an extension. .txt would be the most obvious as most webservers are already configured to serve that extension unlike .json etc. If you need to support both you could request without and if that fails request it with .txt. This will save a universe of problems for end users.

Allow the client to specify the directory /whatever/anything/acme/ where the server can find the file. .well-known is a genuinely terrible thing on Windows because a workaround is required to create .folders.

**Comment by allo-** [comment]
I just had the problem with nginx and linux (see bug linked above).
I guess there is no way to argue with .well-known (its a rather new standard path for doing things like the acme-challenge or similiar, comparable to DNS TXT-Records), but the content-type requirement seems arbitrary.
There is no way the user needs to interact with the URL anyway (so it's irrelevant for example whan a browser does not display it as text) and the CA can fetch the file without having to check the content-type.
On the other hand a .txt extension would be an easy way to ensure text/plain for most webservers.

**Comment by Lone-Coder** [comment]
It's not just the mime type that is causing a problem on windows & IIS. When ASP.net is installed there's a problem with it's handler eating all the extensionless requests. To fix it the user has to go into the IIS manager and change the order of the handlers which can easily cause a site to break or cause a security hole.

**Comment by My1** [comment]
well that's how I like it...
